### PR TITLE
Windows Swarm template and PowerShell script

### PR DESCRIPTION
**Pull request by neilpeterson**

### CODE REVIEW

**Comment by rgardler** [comment]
Thanks Neil,

There are many whitespace changes in here that are unnecessary and will confuse things for us when we do a diff in order to merge these back into the /parts folder which is how we build these templates.

I'll find some time to pull out the important stuff though and bring that across. Thank you for doing this.

**Comment by neilpeterson** [comment]
Thanks Ross - I've fixed the white space issue. Looks like this came from copying the raw source from GitHub. I have not re-tested the template, but looks accurate to me.

**Comment by neilpeterson** [comment]
Template is good. I've also made some 'formality' additions to the template and PowerShell script.

**Comment by neilpeterson** [comment]
@rgardler @taylorb-microsoft - friendly ping on this one.

**Comment by rgardler** [comment]
Thanks Neil, sorry I meant to close this. The ACS engineering team have moved your work over to their templates.

**Pull request closed without merging**
